# Generated by Django 2.1.7 on 2019-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='type_for_customer',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='type_for_designer',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
