# Generated by Django 2.1.7 on 2019-03-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190316_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image_file',
            field=models.FileField(null=True, upload_to='static/images/'),
        ),
    ]
