# Generated by Django 2.1.7 on 2019-03-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_design_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='image_file',
        ),
    ]
